### ISSUE TITLE
No cursor in GUI | Format Issues

### ISSUE THREAD

**Issue by MusicalCookie** [ReflxctionDev/NameFormatter#3]
Hey,

2 bugs I've come across. Whilst in the /nameformatter format GUI your mouse cursor will not show up.

The tag that the mod adds above impurity members takes the colour of their rank, leaving the actual IGN White.

![2018-03-17_00 03 46](https://user-images.githubusercontent.com/32026336/37549395-710ee628-2977-11e8-83c7-446e0a7d7d41.png)

**Comment by LemmoTresto** [comment]
Second bug already submitted in #2

**Comment by Revxrsal** [comment]
This issue has been reported before. Should be fixed in 1.3. Thanks for reporting
